#!/bin/sh

script_path=$(readlink --canonicalize "$0")
script_bin=$(dirname "${script_path}")
script_name=$(basename "${script_path}")

exec "${script_bin}/tpm-graphs" --db "postgresql://${USER}@/${DATABASE:-tpm}" "$@"
